/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jpaw_fixedpoint_FixedPointNative */

#ifndef _Included_de_jpaw_fixedpoint_FixedPointNative
#define _Included_de_jpaw_fixedpoint_FixedPointNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jpaw_fixedpoint_FixedPointNative
 * Method:    multdiv128
 * Signature: (JJJI)J
 */
JNIEXPORT jlong JNICALL Java_de_jpaw_fixedpoint_FixedPointNative_multdiv128
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
